services:
  db:
    image: postgres:15
    env_file: .env
    environment:
       POSTGRES_PASSWORD: password
       volumes:
        - ./local-db:/var/lib/postgresql/data
     
  web:
    build: .
    ports:
     - 8000:8000

    volumes:
      - ./mysite:/app
    env_file: .env
    links:
      - db
    depends_on:
      - db